# Generated by Django 3.2.4 on 2021-06-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinwin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatoruser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
